name: Changelog
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main

jobs:
  git_cliff:
    name: Git Cliff
    runs-on: ubuntu-latest
    # skip if this is a bot or the PR has the skip-changelog label
    # note that the towncrier check command can recognize a release PR, by looking
    # for changes to the CHANGELOG.md file.
    if: |
      !(
           github.event.pull_request.user.login == 'dependabot[bot]'
        || contains(github.event.pull_request.labels.*.name, 'skip-changelog')
      )
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: pyproject.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
